//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notesplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class download
    {
        public int id { get; set; }
        public Nullable<int> noteid { get; set; }
        public int sellerid { get; set; }
        public int buyerid { get; set; }
        public System.DateTime requesteddate { get; set; }
        public Nullable<bool> ispaid { get; set; }
        public Nullable<bool> isapproved { get; set; }
        public Nullable<System.DateTime> approveddate { get; set; }
        public Nullable<bool> isdownloaded { get; set; }
        public Nullable<System.DateTime> downloadedate { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public int purchaseprice { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users2 { get; set; }
        public virtual notedetails notedetails { get; set; }
        public virtual users users3 { get; set; }
    }
}
