//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notesplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class notedetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notedetails()
        {
            this.download = new HashSet<download>();
            this.noteattachment = new HashSet<noteattachment>();
            this.reviews = new HashSet<reviews>();
            this.spam = new HashSet<spam>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public int statusid { get; set; }
        public Nullable<int> actionby { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> approveddate { get; set; }
        public string title { get; set; }
        public Nullable<int> totalspam { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string displaypicture { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> numberofpages { get; set; }
        public string description { get; set; }
        public Nullable<int> countryid { get; set; }
        public string universityname { get; set; }
        public string coursename { get; set; }
        public string coursecode { get; set; }
        public string professor { get; set; }
        public bool ispaid { get; set; }
        public Nullable<int> sellprice { get; set; }
        public string notepreviewfile { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual category category { get; set; }
        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<download> download { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<noteattachment> noteattachment { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users2 { get; set; }
        public virtual statustype statustype { get; set; }
        public virtual notetype notetype { get; set; }
        public virtual users users3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reviews> reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spam> spam { get; set; }
    }
}
